# Generated by Django 5.2.14 on 2026-07-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_item_image_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_cache_format',
            field=models.CharField(choices=[('jpg', 'JPEG'), ('webp', 'WebP')], default='jpg', max_length=4),
        ),
    ]
