# Generated by Django 5.2.14 on 2026-07-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_item_image_cache_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_locked',
            field=models.BooleanField(default=False),
        ),
    ]
