# Generated by Django 5.2.14 on 2026-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_item_image_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_original',
            field=models.URLField(blank=True, default=''),
        ),
    ]
