# Generated by Django 5.2.14 on 2026-07-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_genre_item_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='media_format',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
