# Generated by Django 5.2.16 on 2026-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_game_launcher_historicalgame_launcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='launcher',
            field=models.CharField(choices=[('Steam', 'Steam'), ('GOG', 'GOG'), ('Epic', 'Epic'), ('EA', 'EA'), ('Ubisoft', 'Ubisoft'), ('Blizzard', 'Blizzard'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Playstation', 'Playstation'), ('Emulation', 'Emulation'), ('Rockstar', 'Rockstar'), ('Amazon', 'Amazon'), ('Other', 'Other')], default='Steam', max_length=11),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='launcher',
            field=models.CharField(choices=[('Steam', 'Steam'), ('GOG', 'GOG'), ('Epic', 'Epic'), ('EA', 'EA'), ('Ubisoft', 'Ubisoft'), ('Blizzard', 'Blizzard'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Playstation', 'Playstation'), ('Emulation', 'Emulation'), ('Rockstar', 'Rockstar'), ('Amazon', 'Amazon'), ('Other', 'Other')], default='Steam', max_length=11),
        ),
    ]
