# Generated by Django 5.2.17 on 2026-10-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_add_lego_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Boardgame'), ('lego', 'Lego')], default='movie', max_length=10),
        ),
    ]
