# Generated by Django 5.2.14 on 2026-07-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_item_image_cache_format'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0055_user_jellyfin_mark_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='UI color theme', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('theme__in', ['dark', 'light'])), name='theme_valid'),
        ),
    ]
