# Generated by Django 5.2.14 on 2026-07-03 00:54

from django.db import migrations, models


def rename_light_to_grey(apps, schema_editor):
    """Convert rows saved under the old 'light' value before the constraint lands."""
    User = apps.get_model("users", "User")
    User.objects.filter(theme="light").update(theme="grey")


def rename_grey_to_light(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(theme="grey").update(theme="light")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_item_image_cache_format'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0056_user_theme_user_theme_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='theme_valid',
        ),
        migrations.RunPython(rename_light_to_grey, rename_grey_to_light),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('grey', 'Grey')], default='dark', help_text='UI color theme', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('theme__in', ['dark', 'grey'])), name='theme_valid'),
        ),
    ]
