# Generated by Django 5.2.14 on 2026-07-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_remove_user_theme_valid_alter_user_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='', help_text='URL of a profile image; cached locally when saved.', max_length=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='image_cached',
            field=models.BooleanField(default=False),
        ),
    ]
