# Generated by Django 5.2.14 on 2026-07-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_user_image_user_image_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_crop',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
