# Generated by Django 5.2.14 on 2026-07-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_user_image_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_media_order',
            field=models.TextField(default='', help_text='Comma-separated media type order for the home screen.'),
        ),
    ]
