# Generated by Django 5.2.14 on 2026-07-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_user_home_media_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_continue_story',
            field=models.BooleanField(default=True, help_text='Show the Continue the Story section on the home page'),
        ),
    ]
