# Generated by Django 5.2.16 on 2026-07-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_user_anime_status_alter_user_boardgame_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_layout',
            field=models.CharField(choices=[('list', 'Compact list'), ('grid', 'Cards')], default='list', help_text='Display home screen items as a compact list or card grid.', max_length=10),
        ),
    ]
