# Generated by Django 5.2.16 on 2026-07-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_user_colored_grid_progress_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='planning_term',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('backlog', 'Backlog')], default='wishlist', help_text='Preferred name for media planned for later.', max_length=10),
        ),
    ]
