# Generated by Django 5.2.16 on 2026-07-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_user_auto_mark_previous_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auto_mark_previous_episodes',
            field=models.BooleanField(default=True, help_text='Mark earlier TV episodes watched when tracking a later episode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clickable_media_cards',
            field=models.BooleanField(default=True, help_text='Hide hover overlay on touch devices'),
        ),
        migrations.AlterField(
            model_name='user',
            name='colored_grid_progress_buttons',
            field=models.BooleanField(default=False, help_text='Show red and green backgrounds on grid progress buttons.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hide_completed_recommendations',
            field=models.BooleanField(default=True, help_text='Hide completed media in recommendations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_layout',
            field=models.CharField(choices=[('list', 'Compact list'), ('grid', 'Cards')], default='grid', help_text='Display home screen items as a compact list or card grid.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='obfuscate_unseen_episodes',
            field=models.BooleanField(default=True, help_text='Blur unseen episode images and descriptions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_all_home_items',
            field=models.BooleanField(default=False, help_text='Show every item in each home screen row without a load button.'),
        ),
    ]
